var express = require('express');
var router = express.Router();

var glossery = [
  {terminology :"DevOps",description:"DevOps is a set of practices and cultural philosophies that aim to bridge the gap between software development (Dev) and IT operations (Ops). It promotes collaboration, communication, and integration between development and operations teams throughout the software development lifecycle.",reference:"'DevOps,' Atlassian. Available: https://www.atlassian.com/devops. "},
  {terminology :"Continuous Integration (CI)",description:"Continuous Integration (CI) is a software development practice where code changes are automatically integrated into a shared repository and verified through automated build and test processes.",reference:'Wikipedia, "Continuous Integration," Wikipedia. Available: https://en.wikipedia.org/wiki/Continuous_integration. '},
  {terminology: "Continuous Deployment (CD)",description:"An extension of continuous integration called continuous deployment (CD) involves automatically deploying code modifications to live environments after they have passed automated testing. The goal of CD is to reduce manual intervention in the deployment process, allowing for quicker and more frequent software update releases.",reference:'GitLab, "Continuous Integration," GitLab, [Online]. Available: https://about.gitlab.com/features/continuous-integration/.'},
  {terminology: "Infrastructure as Code (IaC)",description:"Using configuration files, automation tools, and code, infrastructure resources (such as virtual machines, networks, and storage) are specified and maintained. This practise is known as infrastructure as code (IaC).",reference:'HashiCorp, "What is Infrastructure as Code?," HashiCorp Resources. Available: https://www.hashicorp.com/resources/what-is-infrastructure-as-code.'},
  {terminology: "Microservices",description:"A software architectural technique known as microservices divides an application into small, independent services that may be created, deployed, and maintained independently. Each microservice concentrates on carrying out a particular business function, and they interact with one another via clearly defined APIs.",reference:'Martin Fowler, "Microservices,". Available: https://martinfowler.com/articles/microservices.html.'},
  {terminology: "Docker",description:"With the help of the open-source platform Docker, developers may package apps and their dependencies into small, portable containers. Containers make it simpler to deploy apps on any system that supports Docker because they provide a consistent environment throughout various stages of the development and deployment process.",reference:'Docker, "What is a Container?," Docker. Available: https://www.docker.com/resources/what-container/.'},
  {terminology: "Kubernetes",description:"K8s, or Kubernetes, is a popular abbreviation for this open-source container orchestration system. It automates the installation, expansion, and administration of containerized applications across host clusters.",reference:'The Kubernetes Authors, "Overview," Kubernetes. Available: https://kubernetes.io/docs/concepts/overview/.'},
  {terminology: "Version Control",description:"Developers can manage changes to their codebase over time using a technique called version control, commonly referred to as source control. It facilitates keeping track of changes, managing various code versions, collaborating with other team members, and going back to earlier states as necessary.",reference:'Atlassian, "What is Version Control?," Atlassian Git Tutorials. Available: https://www.atlassian.com/git/tutorials/what-is-version-control.'},
  {terminology: "Agile Development",description:"Software development using the agile methodology places a strong emphasis on adaptability, client collaboration, and responsiveness to changing requirements. It encourages flexible planning, regular software delivery, and ongoing development via frequent feedback loops.",reference:'Atlassian, "Agile," Atlassian. Available: https://www.atlassian.com/agile.'},
  {terminology: "Scrum",description:"Scrum is an agile methodology for organising and managing work, especially in projects involving software development. It entails segmenting activities into sprints, which are time-boxed iterations that last between two and four weeks.",reference:'Atlassian, "Scrum," Atlassian Agile, . Available: https://www.atlassian.com/agile/scrum.'},
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Cloud Glossary' ,glossery:glossery});
});

module.exports = router;
