var express = require('express');
var router = express.Router();

var glossery = [
  {terminology :"DevOps",description:"DevOps is a set of practices and cultural philosophies that aim to bridge the gap between software development (Dev) and IT operations (Ops). It promotes collaboration, communication, and integration between development and operations teams throughout the software development lifecycle.",reference:"'DevOps,' Atlassian. Available: https://www.atlassian.com/devops. "},
  {terminology :"Continuous Integration (CI)",description:"Continuous Integration (CI) is a software development practice where code changes are automatically integrated into a shared repository and verified through automated build and test processes.",reference:'Wikipedia, "Continuous Integration," Wikipedia. Available: https://en.wikipedia.org/wiki/Continuous_integration. '},
  {terminology: "Continuous Deployment (CD)",description:"An extension of continuous integration called continuous deployment (CD) involves automatically deploying code modifications to live environments after they have passed automated testing. The goal of CD is to reduce manual intervention in the deployment process, allowing for quicker and more frequent software update releases.",reference:'GitLab, "Continuous Integration," GitLab, [Online]. Available: https://about.gitlab.com/features/continuous-integration/.'},
  {terminology: "Infrastructure as Code (IaC)",description:"Using configuration files, automation tools, and code, infrastructure resources (such as virtual machines, networks, and storage) are specified and maintained. This practise is known as infrastructure as code (IaC).",reference:'HashiCorp, "What is Infrastructure as Code?," HashiCorp Resources. Available: https://www.hashicorp.com/resources/what-is-infrastructure-as-code.'},
  {terminology: "Microservices",description:"A software architectural technique known as microservices divides an application into small, independent services that may be created, deployed, and maintained independently. Each microservice concentrates on carrying out a particular business function, and they interact with one another via clearly defined APIs.",reference:'Martin Fowler, "Microservices,". Available: https://martinfowler.com/articles/microservices.html.'},
  {terminology: "Docker",description:"With the help of the open-source platform Docker, developers may package apps and their dependencies into small, portable containers. Containers make it simpler to deploy apps on any system that supports Docker because they provide a consistent environment throughout various stages of the development and deployment process.",reference:'Docker, "What is a Container?," Docker. Available: https://www.docker.com/resources/what-container/.'},
  {terminology: "Kubernetes",description:"K8s, or Kubernetes, is a popular abbreviation for this open-source container orchestration system. It automates the installation, expansion, and administration of containerized applications across host clusters.",reference:'The Kubernetes Authors, "Overview," Kubernetes. Available: https://kubernetes.io/docs/concepts/overview/.'},
  {terminology: "Version Control",description:"Developers can manage changes to their codebase over time using a technique called version control, commonly referred to as source control. It facilitates keeping track of changes, managing various code versions, collaborating with other team members, and going back to earlier states as necessary.",reference:'Atlassian, "What is Version Control?," Atlassian Git Tutorials. Available: https://www.atlassian.com/git/tutorials/what-is-version-control.'},
  {terminology: "Agile Development",description:"Software development using the agile methodology places a strong emphasis on adaptability, client collaboration, and responsiveness to changing requirements. It encourages flexible planning, regular software delivery, and ongoing development via frequent feedback loops.",reference:'Atlassian, "Agile," Atlassian. Available: https://www.atlassian.com/agile.'},
  {terminology: "Scrum",description:"Scrum is an agile methodology for organising and managing work, especially in projects involving software development. It entails segmenting activities into sprints, which are time-boxed iterations that last between two and four weeks.",reference:'Atlassian, "Scrum," Atlassian Agile, . Available: https://www.atlassian.com/agile/scrum.'},
  {terminology: "Git", description: "Git is a distributed version control system widely used for tracking changes in source code during software development. It allows multiple developers to collaborate on a project, manage different versions of files, and merge their changes efficiently. ", reference: 'Atlassian, "What is Git?," Atlassian, Date of publication or update not specified. Available: https://www.atlassian.com/git/tutorials/what-is-git.'},
  {terminology: "Puppet", description: "Puppet is an open-source configuration management tool used for automating the deployment and management of software and system configurations. It allows administrators to define desired states for resources on target systems and ensures that the systems remain in the desired state.", reference: 'Puppet, "What is Puppet?," Puppet Resources, Date of publication or update not specified. Available: https://www.puppet.com/resources/what-is-puppet/. '},
  {terminology: "Ansible", description: "Ansible is an open-source automation tool that simplifies IT orchestration, application deployment, and configuration management. It uses a simple and human-readable language (YAML) to define tasks, allowing users to easily manage and automate complex workflows.", reference: 'Red Hat, "What is Ansible?," Red Hat, Date of publication or update not specified. Available: https://www.redhat.com/en/topics/automation/what-is-ansible.'},
  {terminology: "Load Balancing", description: "Load balancing is a technique used to distribute incoming network traffic across multiple servers or resources to ensure optimal resource utilization, prevent overload, and enhance performance and availability.", reference: 'F5, "Load Balancing," F5 Services Resources, Date of publication or update not specified. Available: https://www.f5.com/services/resources/glossary/load-balancing. '},
  {terminology: "Infrastructure Monitoring", description: "Infrastructure monitoring involves the continuous tracking and analysis of various components in an IT environment, such as servers, networks, and databases. ", reference: 'SolarWinds, "What is Infrastructure Monitoring?," SolarWinds IT Monitoring, Date of publication or update not specified. Available: https://www.solarwinds.com/it-monitoring/what-is-infrastructure-monitoring.'},
  {terminology: "Scalability", description: "Scalability is the ability of a system or application to handle increasing workloads and user demands. It can be achieved by adding resources, such as servers or computing power, to accommodate higher loads without compromising performance or responsiveness.", reference: 'Amazon Web Services, "Scalability," Available: https://aws.amazon.com/architecture/builders-library/scalability/. '},
  {terminology: "Elasticity", description: "Elasticity refers to the capability of a system to automatically and dynamically scale resources up or down based on demand. It allows applications to adapt to varying workloads and ensure efficient resource utilization, especially in cloud computing environments.", reference: 'Amazon Web Services, "Elasticity," What is Cloud Computing?. Available: https://aws.amazon.com/what-is-cloud-computing/elasticity/.'},
  {terminology: "Incident Management", description: "Incident management is a process that focuses on quickly identifying, responding to, and resolving disruptions or incidents in an IT environment.", reference: 'Atlassian, "Incident Management Process," Atlassian, Date of publication or update not specified. Available: https://www.atlassian.com/incident-management/process. '},
  {terminology: "ChatOps", description: "ChatOps is a collaborative approach to DevOps that involves integrating chat platforms and bots into the development and operations workflow. It enables teams to perform actions, trigger deployments, and monitor systems through conversational interfaces, improving communication, transparency, and automation.", reference: 'GitHub, "ChatOps: A guide to getting started," GitHub Blog, April 7, 2016. Available: https://github.blog/2016-04-07-chatops-a-guide-to-getting-started/.'},
  {terminology: "Canary Deployment", description: "Canary deployment is a deployment strategy that involves gradually rolling out new software updates to a small subset of users or servers before applying changes to the entire infrastructure. ", reference: 'Google Cloud, "Canary Deployment using Kubernetes Engine," Google Cloud Architecture, Date of publication or update not specified. Available: https://cloud.google.com/architecture/canary-deployment-using-kubernetes-engine.'},
  {terminology: "Change Management",description: "A methodical approach to organising, carrying out, and managing changes inside an organisation is known as 'change management'. It makes sure that changes are implemented successfully, minimising risks and disruptions while maximising benefits, whether they are in technology, procedures, or policies." ,reference:"P. Inc., “Change Management | What is Change Management | Prosci,” Change Management | What is Change Management | Prosci. https://www.prosci.com/change-management"},
  {terminology: "GitLab",description: "GitLab is a web-based platform that provides a complete DevOps lifecycle toolchain. It offers features for version control (Git repository hosting), CI/CD, issue tracking, code review, and more, all integrated into a single platform.",reference:"“The DevSecOps Platform,” The DevSecOps Platform | GitLab. https://about.gitlab.com/"},
  {terminology: "Infrastructure Automation",description: "Infrastructure Automation is the practice of using scripts, code, or tools to automate the provisioning, configuration, and management of infrastructure components, such as servers, networks, and databases. This approach reduces manual effort, improves consistency, and enables efficient scaling.",reference: "“What is Infrastructure Automation? | VMware Glossary,” VMware. https://www.vmware.com/topics/glossary/content/infrastructure-automation.html"},
  {terminology: "Chaos Engineering",description: "Chaos Engineering is a practice that involves deliberately introducing controlled chaos or failures into a system to assess its resilience and identify weaknesses. It helps organizations build more robust and reliable systems by proactively finding and fixing vulnerabilities.",reference: "“PRINCIPLES OF CHAOS ENGINEERING - Principles of chaos engineering,” PRINCIPLES OF CHAOS ENGINEERING - Principles of chaos engineering. https://principlesofchaos.org/"},
  {terminology: "Version Control System (VCS)",description: "A Version Control System (VCS) is a software tool that manages changes to source code and other files. It records every change made to the codebase, allowing developers to track revisions, collaborate effectively, and revert to previous versions if needed.",reference: "“About Git - GitHub Docs,” GitHub Docs. https://ghdocs-prod.azurewebsites.net/en/get-started/using-git/about-git"},
  {terminology: "Service Level Agreement (SLA)",description: "A Service Level Agreement (SLA) is a formal agreement that defines the level of service a customer can expect from a service provider. It outlines specific metrics, response times, and responsibilities, ensuring clear expectations and accountability.",reference:"“What is a Service-Level Agreement (SLA)?,” IT Channel, Jan. 01, 2021. https://www.techtarget.com/searchitchannel/definition/service-level-agreement"},
  {terminology: "Artifact",description:"An artifact in DevOps refers to any digital output or result of a software development process. This includes compiled code, libraries, executables, configuration files, and documentation. Artifacts are typically stored in a repository and can be deployed to various environments.",reference:"“Artifact | JFrog,” JFrog. https://jfrog.com/glossary/artifact/"},
  {terminology: "Incident Response",description: "Incident Response is a structured approach to addressing and managing security incidents, data breaches, or system failures. It involves detecting, analyzing, mitigating, and recovering from incidents while minimizing damage and ensuring compliance with relevant regulations.",reference:"“Advanced Persistent Threat Activity Targeting Energy and Other Critical Infrastructure Sectors | CISA,” Cybersecurity and Infrastructure Security Agency CISA, Mar. 15, 2018. https://www.cisa.gov/news-events/alerts/2017/10/20/advanced-persistent-threat-activity-targeting-energy-and-other"},
  {terminology: "Zero Trust Security",description: "Zero Trust Security is a security model based on the principle of not trusting any entity, whether internal or external to the organization, until they have been verified and authenticated. It assumes that threats can exist both inside and outside the network and requires continuous verification and monitoring of users and devices.",reference:"“Enable Your Zero Trust Security | Akamai,” Akamai. https://www.akamai.com/solutions/security/zero-trust-security"},
  {terminology: "Blue-Green Deployment",description:"Blue-Green Deployment is a release management strategy that involves maintaining two separate environments (blue and green) with identical configurations. When a new version of an application is ready, it is deployed to one environment (e.g., green) while the other (e.g., blue) remains in production. This allows for seamless switching between environments to minimize downtime and rollback easily if issues are detected.",reference:"M. Fowler, “bliki: BlueGreenDeployment,” martinfowler.com, Mar. 01, 2010. https://martinfowler.com/bliki/BlueGreenDeployment.html"},
  {terminology: "Continuous Testing",description: "Continuous testing is the practice of running automated tests continuously throughout the software development lifecycle. It ensures that code changes do not introduce new bugs or regressions.",reference:"'Continuous Testing', avaible: https://www.tricentis.com/continuous-testing/"},
  {terminology: "Container Orchestration",description: "Container orchestration is the management and automation of containerized applications, including tasks like deployment, scaling, and load balancing. ",reference:"“Overview,” Kubernetes. https://kubernetes.io/docs/concepts/overview/"},
  {terminology: "Immutable Infrastructure",description: "Immutable infrastructure is a concept where server instances are never modified after they are created. Instead, new instances are created with updates, reducing configuration drift. ",reference:"'What is Immutable Infrastructure?', avaible: https://www.hashicorp.com/resources/what-is-immutable-infrastructure"},
  {terminology: "Serverless Computing",description: "Serverless computing is a cloud computing model where developers write code that runs in response to events, without needing to manage servers or infrastructure.",reference:"“Serverless Computing – Amazon Web Services,” Amazon Web Services, Inc. https://aws.amazon.com/serverless/"},
  {terminology: "Configuration Management",description: "Configuration management is the process of automating and managing the configuration of servers and infrastructure, ensuring consistency and reproducibility.",reference:"“What is configuration management,” What is configuration management, Jun. 22, 2023. https://www.redhat.com/en/topics/automation/what-is-configuration-management"},
  {terminology: "Infrastructure as a Service (IaaS)",description: "IaaS is a cloud computing service model that provides virtualized computing resources over the internet, allowing users to rent infrastructure like virtual machines. ",reference:"“What is IaaS? Infrastructure as a Service | Microsoft Azure,” What is IaaS? Infrastructure as a Service | Microsoft Azure. https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-iaas"},
  {terminology: "Containerization",description: "Containerization is a method of packaging, distributing, and managing applications and their dependencies in containers, such as Docker containers.",reference:"“What is a Container? | Docker,” Docker. https://www.docker.com/resources/what-container/"},
  {terminology: "Serverless Monitoring",description: "Serverless monitoring involves tracking and analyzing the performance and behavior of serverless applications, helping teams optimize and troubleshoot them. ",reference:"'Serverless Monitoring' Avaiable: https://www.datadoghq.com/serverless-monitoring/"},
  {terminology: "Infrastructure as Code (IaC) Framework",description: "IaC frameworks provide a structured approach to defining and provisioning infrastructure using code, enhancing automation and reproducibility. ",reference:"“What is Infrastructure as Code with Terraform? | Terraform | HashiCorp Developer,” What is Infrastructure as Code with Terraform? | Terraform | HashiCorp Developer. https://developer.hashicorp.com/terraform/tutorials/aws-get-started/infrastructure-as-code"},
  {terminology: "ChatOps",description: "ChatOps is a collaboration model that integrates chat tools with automation, enabling teams to manage and monitor their infrastructure and workflows through chat interfaces.",reference:"'What is ChatOps?' Avaiable:https://www.atlassian.com/blog/software-teams/what-is-chatops"},
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Cloud Glossary' ,glossery:glossery});
});

module.exports = router;
